apiVersion: v1
kind: Pod
metadata:
  name: rosbridge
  labels:
    name: rosbridge
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: {{.Release.Service | quote }}
    # The "release" convention makes it easy to tie a release to all of the
    # Kubernetes resources that were created as part of that release.
    release: {{.Release.Name | quote }}
    # This makes it easy to audit chart usage.
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  containers:
    - env:
        - name: ROS_HOSTNAME
          value: rosbridge
        - name: ROS_MASTER_URI
          value: http://master:11311
      name: rosbridge
      image: loeh/ros_bridge_node:latest
      ports:
        - containerPort: 11311
          name: master
        - containerPort: 9090
          name: rosbridge
