apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  containers:
   -  name: webapp
      image: loeh/e2eturtlebotwebapp:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 5000
          name: webapp
